### ISSUE TITLE
Beta version problem with Internal Flash

### ISSUE THREAD

**Issue by Fires04** [FrSky-OS/X12S-bug-report#10]
Hi, I got problem with our Horus ( beta HW ), it starts show internal flash memory error. Everything other looks ok. Any suggestion ?

I try:
- reflash
- format

If I connect Horus to PC, I see two massstorages one ( sd card is ok ), but internal flash ( needs be formated, but unable to format)

Firmware version : **FrSky-OS v1.2.21**

![screen_x12s](https://cloud.githubusercontent.com/assets/699214/20306596/59f50d84-ab3b-11e6-969c-b3c3784909f4.jpg)

**Comment by MIKE-DAILEY** [comment]
If your system is a beta unit with all original beta hardware there is no Flash Memory drive.  And of course the FrTX OS shows the yellow triangle indicating that the Flash Memory drive is not working.  The beta system only use the SD card.

**Comment by Fires04** [comment]
ok thanks for info

**Comment by MIKE-DAILEY** [comment]
You might want to contact your FrSky dealer that provided the beta unit to learn the options that FrSky offered beta testers.

**Comment by Fires04** [comment]
I'm beta tester, but I did not find specification of beta radios :)

**Comment by MIKE-DAILEY** [comment]
Contact your dealer for the options offered to the beta testers.
