### ISSUE TITLE
1.3.01 Alti-v and Alti-g does not acquire 

### ISSUE THREAD

**Issue by MIKE-DAILEY** [FrSky-OS/X12S-bug-report#106]
1.3.01 Alti-v and Alti-g does not acquire.

**Comment by n1973w** [comment]
also now in 1.4.01   :-).. You cant just brake code and not fix it for ever and ever..

**Comment by MIKE-DAILEY** [comment]
I reported it when I was testing the pre-beta and again with 1.4.01.

**Comment by strgaltdel** [comment]
Ich kehre zurück am 13.08.2017.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [FrSky-OS/X12S-bug-report]
1.3.01 Alti-v and Alti-g does not acquire (#106)" gesendet am 02.08.2017 01:09:18.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by strgaltdel** [comment]
Ich kehre zurück am 13.08.2017.

Guten Tag,

ich bin bis zum o.g. Termin nicht erreichbar.
In dringenden Fällen können sie telefonisch die Zentrale unter 02173 950-5 erreichen und sich mit
dem jeweils zuständigen Kollegen verbinden lassen.

Danke


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [FrSky-OS/X12S-bug-report]
1.3.01 Alti-v and Alti-g does not acquire (#106)" gesendet am 02.08.2017 01:53:31.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während diese Person abwesend ist.

**Comment by Nesan65** [comment]
is there any other way to work on veriometer ? why no solution yet

**Comment by MIKE-DAILEY** [comment]
FrSky found what was causing the problem in 1.3.01 and 1.4.01 and are working on a solution.

**Comment by Nesan65** [comment]
thanks Mike-Dailey the newer version 1.4.02 beta cure the veriometer problem!
Thank you Love Horus x12s.! and recommending to other co flyers.

**Comment by MIKE-DAILEY** [comment]
Many thanks to the folks at FrSky that fixed the problem because it was complicated.
