### ISSUE TITLE
Timer as LSW

### ISSUE THREAD

**Issue by Nesan65** [FrSky-OS/X12S-bug-report#123]
1.4.02(Beta)
HI I Try to use the timer as trigger to a function.  but it seems not working. could some one check it please.
if it work can we use it as sequencer?

**Comment by MIKE-DAILEY** [comment]
It looks like the CONST value cannot determine the timer value.   Is the CONST SRC 2 seconds, min, hours?

Mike

**Comment by Nesan65** [comment]
even I tried like "Timer1 > Timer2"  not working.
but "Timer1=Timer2" is ok ???@#*~*

**Comment by Adelaxie** [comment]
@Nesan65  We modified it months ago, do you mean it still doesnot work? we tested it ok.

**Comment by MIKE-DAILEY** [comment]
How does the CONST value relate to the timer.  Is the CONST number seconds?

**Comment by Nesan65** [comment]
I think it is not working or may be I do not configure properly.! in this case please let me know one sample please.

**Comment by Nesan65** [comment]
can anybody explain how to do it Timer as LSW Please. I could not do it!

**Comment by MIKE-DAILEY** [comment]
I guess I don't understand how the feature works.  I thought you could use a logic switch that would go true when the counter went over or under a counter number set in CONST, but I'm not able to make it work.

**Comment by MIKE-DAILEY** [comment]
Tested in the next firmware to be released.  The CONST is in seconds.  So if the timer starts a 2 min and you want the LS to be true on count down to 1 min the CONST is set at 60.

**Comment by Nesan65** [comment]
So it is not working in F.W 1.4.02(Beta). and do could you say approx when they release it?
Any way thank you for let me know about this.

**Comment by MIKE-DAILEY** [comment]
It would not work for me in 1.4.02, but does in the next beta to be released.  Don't know when it will be released.
