### ISSUE TITLE
1.4.02 - Joystick, logical switch and play track with special function

### ISSUE THREAD

**Issue by goryc** [FrSky-OS/X12S-bug-report#124]
With the new firmware 1.4.02 does not work anymore, first worked perfectly!!!

![horus00000006](https://user-images.githubusercontent.com/28689372/29935608-9ae4cef6-8e7f-11e7-9915-42d33d8884b6.JPG)

 See the last row LSW2
![horus00000007](https://user-images.githubusercontent.com/28689372/29935610-a1ddcfb4-8e7f-11e7-8428-5d3475d521e1.JPG)

**Comment by MIKE-DAILEY** [comment]
I tried a simple logic switch to trigger on J1 value being over or under a CONST and the logic switch does not change state for me as well.

**Comment by Adelaxie** [comment]
yes,we are testing the fixed firmware. thanks for feedback. please pay attention on update on website.

**Comment by Nesan65** [comment]
i make it work by assign a channel to M-Y and M-X in EXMixer then call it from LSW it works. and this way two channel can be control by M-X and M-Y. like camera axil

**Comment by Adelaxie** [comment]
fixed on v1.4.3
