### ISSUE TITLE
Mixing throttle differential for twin motors 

### ISSUE THREAD

**Issue by Boroal** [FrSky-OS/X12S-bug-report#125]
Help needed. I have a two motor on channel 3 and 7. I am trying to mix with rudder to get differential thrust. I can mix rudder to throttle in the ex mix but can't work out how to get channels 3 and 7 to move in opposite directions. Can you help?

**Comment by WismyYao** [comment]
FROS is mixed to the function, so if only mixed to the throttle, regardless of setting  the throttle function to any channels, the output is certainly the same. So we can use AUX1, instead of the second throttle, and then mix rud to AUX1, so that you can adjust the mixing direction.

**Comment by Boroal** [comment]
Solved thanks
