### ISSUE TITLE
Overlay and icons missing

### ISSUE THREAD

**Issue by alex998r** [FrSky-OS/X12S-bug-report#127]
Upgraded to the latest 1.4.02 firmware, in the main screen the right top icons are missing ( battery, Rf )
In the second screen the whole overlay is missing
![20170908_200627](https://user-images.githubusercontent.com/29479191/31329798-0c4cf58a-acdc-11e7-8869-b8e35163f81d.jpg)
![20170908_200638](https://user-images.githubusercontent.com/29479191/31329803-0e490d92-acdc-11e7-868e-7128ac58bf3f.jpg)

**Comment by andymeade** [comment]
Confirmed here as well - quite annoying when flying as I have no battery level indicator!

**Comment by MIKE-DAILEY** [comment]
You did not copy all the files provided correctly to the flash memory drive. See steps here https://www.rcgroups.com/forums/showpost.php?p=38101065&postcount=11471

**Comment by alex998r** [comment]
Ok Mike, thanks for the info, now it works
