### ISSUE TITLE
Radio Dead but red light on

### ISSUE THREAD

**Issue by octaviojss** [FrSky-OS/X12S-bug-report#13]
After 2 weeks with the Frsky Horus, today, when i was powering it on, the radio didnt respond, only a red light was on, continuouly, no blinking. I tried holding power button for a while (around 2 minutes, perhaps more) to no avail. Red light is still on, i plugged radio to power supply, but still you have a glimpse of red.
So radio is dead, except for the continuous red light.

**Comment by Adelaxie** [comment]
same with #14,move there please
