### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by mdrjr** [FrSky-OS/X12S-bug-report#133]
How to reset a X12S to factory?

I've flashed new firmware but all my models are there.. I want to clean it like it was new.

**Comment by janekx** [comment]
Delete the bin files from aircraft types in SYSTEM folder on flash. If you will delete transmitterFile.bin it will reset the calibration and setting as well.

**Comment by mdrjr** [comment]
Cleaned the flash and replaced with a new flash content from FrSky website + new firmware.

Very nice now. Will soon start to compete on 424 with my Horus
