### ISSUE TITLE
New model not works

### ISSUE THREAD

**Issue by Drashiel** [FrSky-OS/X12S-bug-report#136]
I created a new airplane model, after update to 1.4.03. After that, I can´t get any output to work. All are to 0 even changing input and output map. On monitor there is no changes even moving all sticks. 
Selecting another model created prior update, works nice even. To get new model I copied prior created and this works.

**Comment by MIKE-DAILEY** [comment]
Did you do the following steps during the 1.4.03 update?

From the FLASH files provided
Copy Flash/CONFIG/*.* to the CONFIG directory;
Copy FLASH/IMAGES/bitmap to the FLASH/IMAGES/bitmap directory;

**Comment by Drashiel** [comment]
Nop, I copied config directory to flash and now works.
Thanks Mike.
