### ISSUE TITLE
FLVSS telemetry issue

### ISSUE THREAD

**Issue by joel-1** [FrSky-OS/X12S-bug-report#16]
FrOS 1.2.21 trying to use 2 FLVSS LiPo sensors, both sensors are from 2016 which is after the last FW update I could find. One sensor is ID2 one sensor is ID4. Only six cells show on the telemetry page. Each sensor works fine by itself. When both sensors are connected with 6S packs only cells 1 - 6 show on the telemetry page. If I remove one of the packs the telemetry screen will momentarily show 0V for all cells then randomly show voltages skipping through cell numbers from the other pack. if I remove the sensor that has no pack connected the display returns to normal. I verified that the sensors have different IDs using the setting tool.

**Comment by Adelaxie** [comment]
IDs  you mean physical ID or group Number?
Or can you tell me how you set the IDs differently?

**Comment by joel-1** [comment]
I used the servo channel changer tool to change the physical ID from 02 ( default ) to 04 on one of the sensors.

**Comment by Adelaxie** [comment]
All the default group number is 0, you need to change other one to 1 (1-15,not 1) to make two sensors that are the same kind to work.
Now ,they send out data with the same application ID and data covers each others' on the sreen.

**Comment by joel-1** [comment]
I used my smart port dashboard to change group ID and still have an issue. My last attempt has one sensor at Phyical ID 2 and Group ID 2 ( bat 1A ), second sensor is Physical ID3 and Group ID 3 bat2 A ). I can get 12 cells to display but it does not seem to behave correctly. If I disconnect bat 1A, celss 1 - 6 go to zero as expected. If I reconnect bat 1A the cells reappear. If I disconnect bat some cells from readout 7-12 disappear and cells randomly appear on 1 - 6. Another issue I notice is I have a cellmin alarm set to repeat every 10 seconds. When I disconnect bat 2A, the alarm is constant and seems out of order. Usually it says cell minimum voltage, warning and repeats every 10 seconds. In bad state is repeats cell minimum voltage sever times in a row ( do delay ), the warning several times in a row ( no delay ).
![2batdisplay](https://cloud.githubusercontent.com/assets/12021514/20641710/50a799c6-b3bb-11e6-9ca0-9f10ee6a791d.JPG)
![bat1a_1b](https://cloud.githubusercontent.com/assets/12021514/20641706/50a35d3e-b3bb-11e6-895b-cdbf582ce806.JPG)
![bat1a_disconnect](https://cloud.githubusercontent.com/assets/12021514/20641711/50ab34a0-b3bb-11e6-9100-b22d451cffc4.JPG)
![bat1a_disconnect_display](https://cloud.githubusercontent.com/assets/12021514/20641709/50a785da-b3bb-11e6-89b0-0bbe2f0f0087.JPG)
![bat2a_disconnect](https://cloud.githubusercontent.com/assets/12021514/20641708/50a64a6c-b3bb-11e6-8312-54d592bd429d.JPG)
![bat2a_disconnect_display](https://cloud.githubusercontent.com/assets/12021514/20641707/50a5c042-b3bb-11e6-9994-43bb77729601.JPG)

**Comment by Adelaxie** [comment]
@joel-1  Will try on this.

**Comment by joel-1** [comment]
I saw in the 1.2.23 release notes this was addressed. I am still seeing the same issue. It is possible that when I unplug a battery it behaves differently than if I just let it run down.

**Comment by Adelaxie** [comment]
Maybe I misunderstood your issue. Can you make a video ?

**Comment by EngelMT** [comment]
We test it also today with 1.2.23. But to get values for 12S is not possible. We st different IDs. In the moment we have no dashboard in stock to set group IDs. Any idea how we or customers can do it without dashboard? With Horus it is not possible to set group IDs.

**Comment by Adelaxie** [comment]
Got the issue. Will fix it. @joel-1

**Comment by joel-1** [comment]
Good, thanks. So you do not need me to make a video?

**Comment by Adelaxie** [comment]
No need. thanks for your feedbacks.

**Comment by EngelMT** [comment]
O.k. hope we get our delivery today incl. FSD. Than I will test and come back.

**Comment by joel-1** [comment]
Should this be checked in .24 when it's out?

**Comment by Adelaxie** [comment]
yes  @joel-1

**Comment by EngelMT** [comment]
Adela, with 1.2.24 is also important to set a group ID or do it work without?

**Comment by joel-1** [comment]
Hi,
The display now works properly but there is still an issue. When using celsmin warning, it only works with cells 1-8. If I unplug cells 9-16 I do not get a warning. Do you want to leave this issue here or start a new one?

Joel

**Comment by Adelaxie** [comment]
a new one please,long post/

**Comment by joel-1** [comment]
Cell display is OK. Closing issue
