### ISSUE TITLE
FrOS 1.2.22 model load issue

### ISSUE THREAD

**Issue by joel-1** [FrSky-OS/X12S-bug-report#17]
When changing models, there is a load error on the first attempt. Trying to load again seems to work fine. Does not seem to happen every time.

**Comment by Adelaxie** [comment]
We will try to reproduce it and fix it.

**Comment by Adelaxie** [comment]
Please test it on v1.2.23 when it is released(not released yet).

**Comment by joel-1** [comment]
This does seem fixed. Closing issue
