### ISSUE TITLE
Flaps and servo slow (SPEED) bug

### ISSUE THREAD

**Issue by dvelez33** [FrSky-OS/X12S-bug-report#18]
Hello,

While configuring one of my Jets on my new Horus, I’ve noticed that when I configure Flaps (FLP) on channel 6 or 7 for that matter - it works as normal. However, as soon as I try adding servo slow/speed the flaps will lock to one side and stop working after rebooting the system, and if you go and look at the servo monitor screen channel 6 (flaps) is pecked to -125, if I remove the servo slow it will start to work correctly again.

Running FrTX OS version 1.2.21.
1. INPUT MAP - Default setting FLP L2 or switch SB
2. OUTPUT MAP - CH6 FLP
3. SPEED - CH 6 - DOWN 10.0
4. MONITOR - L2 full up - CH 6 100
5. MONITOR - L2 move to full down - CH 6 slowly moves to -100
Works OK until you reboot the system.
Thanks,
Doug

**Comment by Adelaxie** [comment]
@dvelez33  Fixed issue? if still issues please create a new one or reopen it.
