### ISSUE TITLE
THR-CURVE

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#29]
How to scroll up if a 21-Point Curve is set?

**Comment by Adelaxie** [comment]
You need to make the edit(point widget) in edit mode(a rectangle around the edit) then press pgup/pgdn to scroll up /down.

**Comment by EngelMT** [comment]
O.k. thanks for explain. Missing in manual! Now our translation is to long and must be changed. But will be no problem.

**Comment by EngelMT** [comment]
o.k. can be closed
