### ISSUE TITLE
SNAP ROLL

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#30]
The SNAP ROLL function is not correct. A SNAP ROLL is flown with ailerons, elevator and side rudders. Side rudder is missing here.

**Comment by Adelaxie** [comment]
What is side rudder ?Please explain more.

**Comment by EngelMT** [comment]
Sorry, in German Seitenruder! So I make a mistake in translation. It is the rudder!

**Comment by EngelMT** [comment]
O.k. seems to be solved in 1.2.25 or I've overlooked it in the past.
