### ISSUE TITLE
1.2.22 Transmitter GPS

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#31]
Does not seem to work. Outdoor even after 10 minutes no display. The display "Dist." completely missing.

**Comment by janekx** [comment]
Need to be chatched for 20-30mins we test it

**Comment by EngelMT** [comment]
O.k. thanks, will test ist again. But it can not be normal I think!

**Comment by MIKE-DAILEY** [comment]
It is much faster finding satellites if you turn off the transmitter RF while it is finding the satellites and then turn the RF back on.

**Comment by EngelMT** [comment]
Thanks Mike. Will test it. But as I wrote I think it can not be normal. All GPS systems in cars find the satelite in a few seconds.

**Comment by EngelMT** [comment]
Mike, you are right. With RF from, the satellites are found within 2 minutes. Bu I missing the term "DIS" and the value to "DIS". Is it a problem of the 1.2.22?

**Comment by MIKE-DAILEY** [comment]
I skipped 1.2.22 because of the model change problem.  I can confirm that the DIS: is on the screen and working in the next build release.

**Comment by EngelMT** [comment]
O.k. thanks

**Comment by Adelaxie** [comment]
The RF module is too near to the GPS so we recommend to turn off the RF module when searching satelites.
DIS should be showed as we test.
Thanks Mike for the answer.

**Comment by EngelMT** [comment]
o.k. thanks. Then this can be closed
