### ISSUE TITLE
Mode selection enhancemen

### ISSUE THREAD

**Issue by janekx** [FrSky-OS/X12S-bug-report#33]
My sugestion is to make general mode setting and selecting of mode for all models or be able to choose every model creation. 
In Sys will be menu Selected mode and switch if mode is for all models. Switch General mode ON/OFF
In case of setting mode and switch that mode is general ON, there will be no mode choosing in model creation process. 
In case of selected mode but not switched general to ON, there will be each model creation process and preselected mode will be based on selected setting. 
 
This will ease the creation of model for most of users 
No more need to distribute mode diferend firmwares

**Comment by Adelaxie** [comment]
This is based on the whole structure horus now use, will not change on this. Please understand.
