### ISSUE TITLE
CMBFLP->ELE speed 

### ISSUE THREAD

**Issue by Fires04** [FrSky-OS/X12S-bug-report#35]
Hi,

FW: 1.2.21
Model type: Airplane

it is possible to setup speed to CMBFLA->ELE mix ? 
I setup flaps, setup SPEED on channel  CH6-CH7(flaps), and activated CMBFLP->ELE on switch. 

But when I check monitor  flas are nice smooth and slow, but change at ELE is instant. It is possible or it is not implemented yet ? 

Thanks

**Comment by Adelaxie** [comment]
This can not ve achieved based on our structure now. sorry for that.
