### ISSUE TITLE
1.2.22 beta date issue.

### ISSUE THREAD

**Issue by octaviojss** [FrSky-OS/X12S-bug-report#38]
Hi, today i updated the horus to the beta 1.2.22 and the date went to 1-3-2017. when i tried to set the date, i couldnt. whenever i pressed ok to alter the date only a square appeared and i cant change it.
Check the image. The time is ok.
![img_20161204_174618](https://cloud.githubusercontent.com/assets/6273660/20868072/2c75e25c-ba4a-11e6-928a-f0d9e4af5c93.jpg)

**Comment by janekx** [comment]
Know bug, but very thanks for reporting. @Adelaxie

**Comment by Adelaxie** [comment]
Please test it on latest firmware(you can get the software in FrSky wevsite download section).

**Comment by Adelaxie** [comment]
Fixed issue.
