### ISSUE TITLE
Trim Horus in mode1

### ISSUE THREAD

**Issue by Salvatico** [FrSky-OS/X12S-bug-report#4]
First of all I am sorry for my "terrible" English
In my Horus I have the following problems:
(firmware FRSKY 1.2.15 and Beta 1.2.20)
in mode1 Glider normal tail, the rudder trim is not working.
In mode1 Glider V-tail, does not work the elevator trim.
Important note: you need to check on the MONITOR screen or with a receiver and servos because in the main screen trim seems to work.

Another important note: In mode1 Airplane V-tail and normal tail the trims  work regularly.

**Comment by tomkfly** [comment]
Are you sure yo meant to close this issue?

**Comment by Salvatico** [comment]
Sorry, my English is very approximate, you can forward this issue?
Grazie
Paolo

**Comment by tomkfly** [comment]
You should only close an issue when the problem is solved. Closing it makes it look like there is no longer a problem.
Your English is fine. I have seen a lot poorer posted by native speakers.

**Comment by MIKE-DAILEY** [comment]
Open!

**Comment by Salvatico** [comment]
Solved the problem with the new 1.2.21 release.
I want to thank Tomkfly and Mike-Dailey for the help.
Regards
Paolo
