### ISSUE TITLE
Field to small

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#40]
MDL/REVERSE term "NORM" do not fit in the field. It is in english and german. So I think it is no localisation problem.

**Comment by Adelaxie** [comment]
I remember we changed NORM to Norm to minimise the string space /Can you check the latest version?

**Comment by EngelMT** [comment]
I have checked the latest version from yesterday. It is "NORM". O.k. it is a solution to use small letters. But it looks much better to use big ones like the other fields.

**Comment by Adelaxie** [comment]
You know,the screen resolution is limited,sometimes we need to sacrifice some beuty.
I will check the Norm again.

**Comment by EngelMT** [comment]
O.k. it is a possibility.
