### ISSUE TITLE
CURVE-LIB Export/Import

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#44]
Has anyone already tested the export and import? I always get error messages. What am I doing wrong or does it really not work?

**Comment by Adelaxie** [comment]
which version do you use? we did not reproduce it.

**Comment by EngelMT** [comment]
I tested it in the moment with 1.2.23LTemp2 1212. Is it the same. Can be a mistake on my side. Please explain how to do export. SD Card is inside. Do I have to create a special folder?

![export curve lib](https://cloud.githubusercontent.com/assets/16795828/21138862/62e507cc-c130-11e6-83a1-4a18fced694a.jpg)

**Comment by Adelaxie** [comment]
#23 closed ,dumplicate post.

**Comment by Adelaxie** [comment]
It is better to take a video of this issue, it works properly for us .

**Comment by EngelMT** [comment]
I do not know wath a video can help but I will send it by skype. If it is my mistake than please expain how to use Export and Import.

**Comment by Adelaxie** [comment]
You must pressed RTN to cancel the name editing,so the name can not be blank ,the error message pop up.

**Comment by EngelMT** [comment]
I do it. In the moment I press the RTN the message pop up.

**Comment by EngelMT** [comment]
Operator error. so I close it.
