### ISSUE TITLE
GYRO Helicopter

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#46]
Now you find there GYRO, GYRO 2 and GYRO 3. I think it must be GYRO 1, GYRO 2 and GYRO 3.

In the moment the term GYRO 1 (pos. 319 on CSV File) is not used. But GYRO is used above GYRO 2 and in the Header below HORUS. So if you change term GYRO to GYRO 1 the header is also GYRO 1.

The assignment is not correct here.

**Comment by Adelaxie** [comment]
Fixed in next release version
