### ISSUE TITLE
RUD->ELE Mixer Glider Mode

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#50]
Is missing in Glider mode. Used and important by Glider Acrobatic pilots for knife flight.

**Comment by Adelaxie** [comment]
Please try to achieve it by extra mixer.
This will change our structure and will do it in lower priority.

**Comment by EngelMT** [comment]
Be sure, if you will make a real good software you must change your structure!! This software has no real future. Sorry, I must tell you because there are to many unlogic parts.
