### ISSUE TITLE
GYRO Multicopter

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#55]
This problem was solved with new Firmware in Helicopter (#46) . But now I find out that it is in Multicopter not solved. Please do it.

You find there GYRO, GYRO 2 and GYRO 3. I think it must be GYRO 1, GYRO 2 and GYRO 3.

In the moment the term GYRO 1 (pos. 319 on CSV File) is not used. But GYRO is used above GYRO 2 and in the Header below HORUS. So if you change term GYRO to GYRO 1 the header is also GYRO 1.

The assignment is not correct here.

**Comment by EngelMT** [comment]
How do you fix it. I think it is not fixed!

**Comment by Adelaxie** [comment]
Please check on latest version. @EngelMT

**Comment by EngelMT** [comment]
Where I can find the latest version? Must 1.2.26L!!

**Comment by Adelaxie** [comment]
Check on v1.2.25. modified it already.

**Comment by EngelMT** [comment]
Seams to be o.k. now, Thanks.
