### ISSUE TITLE
Variometer problems

### ISSUE THREAD

**Issue by soarersteve** [FrSky-OS/X12S-bug-report#57]
Flew the Radian again today with the upgraded sound pack. Unfortunately there are still problems.
I had maximum altitude (maxalti-v) and altitiude (alti-v) showing on the Horus display and also both parameters linked to a special function switch to play value. (Both special function boxes ticked).
Both Maxalti-v and Alti-v displayed correctly on the Horus screen.
When the switch was thrown to announce the current altitude it was accurate until I went over 101.7 metres. After that it continued to announce 101.7 metres despite the display showing the correct altitude.
The announcement for Maximum altitude only ever said zero metres despite the display showing the correct value.

**Comment by Adelaxie** [comment]
On which version of softwares please?

**Comment by soarersteve** [comment]
Software version 1.2.21

Regards
Steve

**Comment by Adelaxie** [comment]
@soarersteve  Please try on latest v1.2.23 in FrSky website download section.

**Comment by soarersteve** [comment]
Please send me the new software by mail and I will try this weekend.
Thanks.

**Comment by Adelaxie** [comment]
@soarersteve  I did not find your mail address from your profile,so here is the software for test:
Caution: This firmware is not fully tested and only for this issue. Please be careful when flying.
[1216_frtx_test_firm.zip](https://github.com/FrSky-OS/X12S-bug-report/files/656177/1216_frtx_test_firm.zip)

**Comment by soarersteve** [comment]
Adela

Thanks for the file.

I see there is no mode1 / mode2 option for the firmware files.

As I am a mode1 flyer will this make any difference?

Regards

Steve 






Sent from Windows Mail





From: Adela
Sent: ‎Friday‎, ‎16‎ ‎December‎ ‎2016 ‎01‎:‎11
To: FrSky-OS/X12S-bug-report
Cc: soarersteve, Mention





@soarersteve I did not find your mail address from your profile,so here is the software for test:
Caution: This firmware is not fully tested and only for this issue. Please be careful when flying.
1216_frtx_test_firm.zip

**Comment by soarersteve** [comment]
Adelaxie
I flew again with the new software and both problems are now fixed!
Thanks for your help.
