### ISSUE TITLE
Special Function - Play Value - Please add Timer1 or Timer2 (Enhancement)

### ISSUE THREAD

**Issue by guys234** [FrSky-OS/X12S-bug-report#6]
Hi,
in Special Function menu, when choosing play value  and assigning a button to it,
there is no option to choose Timer1 or Timer2,
that I would like to have the option that when moving a switch,
the system can give me voice alert of the current time in the timer (i.e actual read 4 miuntes, 30 seconds remaining) and not just the automatically readout every one minute.

Thanks!

**Comment by Adelaxie** [comment]
Will do ,thanks.

**Comment by Adelaxie** [comment]
I think it is fixed already, can you help to check ? @guys234 
If yes,please close this issue .

**Comment by guys234** [comment]
Fixed! thanks for adding this.
