### ISSUE TITLE
S6R somtimes a errors at ppm-signal for Servo

### ISSUE THREAD

**Issue by hrenz** [FrSky-OS/X12S-bug-report#64]
S6R Error
sometime every seconds, sometimes after minutes
see Oszi screen shoot,
the PPM-signal is suddently to long at Ch5 and/or Ch6 (but not at Ch1-Ch4)
then a servo makes a short jump
![s6r_error](https://cloud.githubusercontent.com/assets/6217896/21434479/034d0ab6-c875-11e6-8ed2-a10b5f96a29d.jpg)

There are some videos too to see what happen at a S6R  
a X8R is much more stabil at PPM-Signal compard with a S6R

**Comment by Adelaxie** [comment]
This is fixed in our beta firmware and please keep an eye on the S6R firmware update, thx for reporting.

**Comment by Adelaxie** [comment]
Fixed issue.
