### ISSUE TITLE
Clock goes to slow

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#65]
If you adjust the clock of the transmitter you will find out that you have to adjust again after a few of days. Round about 6 Minutes in 4 days. What the reason can be? Or can it be that the clock stops if the menu "TIME" is open.

**Comment by Adelaxie** [comment]
Still can not reproduce,will keep an eye on it.

**Comment by EngelMT** [comment]
I think it is solved with 1.2.25. In the past if you open the TIME Menü and klick to Time or Format than the clock stoped. And after goes out of this Menü the time is not correct. Now, the clock stoped but after goes out of the settings, the clock is reset to the correct time.
