### ISSUE TITLE
Screen Shot

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#67]
I know that HRenz wrote about it in the past. But I can not find this issue. So again. It is not possible to make Screen Shots from Switch Warning Display and Trottle Warning Display. I think it will not work before the the software is completely advanced.

If possible please modify it so we can make screen shots from all screens.

**Comment by Adelaxie** [comment]
At that time ,the system is not start to work ....

**Comment by EngelMT** [comment]
I was worried that this would be difficult. OK. If it is not possible, then it is just so.
