### ISSUE TITLE
Flight Mode Under Airplane

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#68]
I will remember again to add the flight mode in Airplane!! It is very important because other functions are also working only with one setting for the complete flight. For excample DR/Expo can only be set for the complete flight in Airplane because no possibility to use Flight Modes. But for excample it is important to have 50% servos way for pattern acrobatic and 100% for 3D. Or different servo ways for take off and for normal flight and 3D flight.

If a transmitter need Flight Modes than in this menü! This is a standard function in transmitters with much lower price!!

**Comment by MIKE-DAILEY** [comment]
Working in the 08-16-17 1.4.02 FrTX version.
