### ISSUE TITLE
Logical Switch and Timer Reset (Bug?)

### ISSUE THREAD

**Issue by guys234** [FrSky-OS/X12S-bug-report#7]
I've created a logical switch that uses to switches together.
when Assigning it to reset the timer, the timer is stuck on zero and never starts,
even if the logic switch is not engaged. 
when assigning different switch to reset the timer, it works.
when assigning the logical switch to different function it works.

**Comment by Adelaxie** [comment]
Thanks for your reports.

**Comment by Adelaxie** [comment]
Please check the latest firmware and if it has been already fixed please close the issue. Thanks

**Comment by guys234** [comment]
Fixed! thanks for fixing this!
