### ISSUE TITLE
System reset or shutdown

### ISSUE THREAD

**Issue by joel-1** [FrSky-OS/X12S-bug-report#8]
Hello,

With FrOS 1.2.21 with a heli setup. If I go to the Pit->rudder menu and select LINE as the curve then go to the selection under the switch entry ( is NOR by default ), select it then try to change the entry, the radio will either reset and come back up with no SD card or internal memory found, or just shut off. For me, this is 100% repeatable.

![pit_rudder](https://cloud.githubusercontent.com/assets/12021514/20243153/62e17804-a908-11e6-9aaf-421e360d9447.jpg)

**Comment by Adelaxie** [comment]
Thanks for your reports, we will fix it asap.

**Comment by joel-1** [comment]
I have not tried all other menus, but depending on what you find, you might want to scrub other menu items for the same bug.

**Comment by joel-1** [comment]
Another observation on this. To be consistent with other menus, on the left side where it says switch, this should be changeable from switch to flight mode. In flight mode, the pull down for switch should disappear. In switch mode, the NOR ( Idle up 1, idle up 2, idle up 3) pull down option should not be there. In Only in flight mode does the NOR pull down option make sense. The pitch->rudder mix curve should be settable per flight mode.

**Comment by Adelaxie** [comment]
I think it has been fixed. Can you check it and close the issue if yes?
@joel-1

**Comment by joel-1** [comment]
Seems to work, thanks
