### ISSUE TITLE
Software frosen

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#80]
Today my Horus frosen again after I am working in Helicopter/THR MIX. I have had this problem in the past in Airplane Mode also. I wrote an issue with the titel "instabil Horus".

**Comment by Adelaxie** [comment]
Also L version used?

**Comment by EngelMT** [comment]
Yes L Version.

**Comment by Adelaxie** [comment]
Tested a bug in L version.
