### ISSUE TITLE
LSW need timer setting

### ISSUE THREAD

**Issue by janekx** [FrSky-OS/X12S-bug-report#88]
We forget to add timers as condition for LSW!!!

If we need to start telling timers or make other think based on time we must have to set timer like condition in LSW. 

I sugest to make these conditions

Timer > only left side will be settable - ON in set more then time set  
Timer < only left side will be settable - ON in set less then time set
Timer ] [ both sides will be settable - ON except time between sides  
Timer [ ] both sides will be settable  - ON only in time between sides

**Comment by Adelaxie** [comment]
Added now.
