### ISSUE TITLE
CUSTOM/MIXER and Stick Mode

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#91]
The four mixers AIL, ELE, THR and RUD are the right choice for Stickmode 2. In stick Mode 1, however, the specifications do not change. Then you have ELE on THR and vice versa.

Same in Output!

**Comment by FrSky-GX** [comment]
There  is no mode differences under CUSTOM mode.
We will hide the mode selection when creating new model under CUSTOM mode.

**Comment by EngelMT** [comment]
o.k.
