### ISSUE TITLE
1.2.25L remove switch on active mix will not active it again

### ISSUE THREAD

**Issue by janekx** [FrSky-OS/X12S-bug-report#93]
We have found that in A-N in flap setting if we activate mix and leave --- as switch mix works 
if we choose switch mix work in set switch 
if we remove switch but leave mix activated it is not active and cant be waked up other way then create new model.

**Comment by Adelaxie** [comment]
Will modify it as below:

STATUS: ACT
SWITCH: ---
Mix works.

STATUS: INH
SWITCH: --- / SWx
Mix doesnot work.

STATUS: ACT
SWITCH:  SWx
Mix works when SWx is set.

**Comment by janekx** [comment]
The issue is when remove ACT SWx to ACT --- mix no longer work until make new model

**Comment by Adelaxie** [comment]
@janekx  yes, got your meaning.
