### ISSUE TITLE
Input and Output Maps

### ISSUE THREAD

**Issue by EngelMT** [FrSky-OS/X12S-bug-report#97]
In Airplane, Helicopter and Glider all Output Maps are the same. No matter which stick mode was selected.

But in Glider V-Tail the Output is different. Stick Mode 1, 3, 4 are the same. But Stick Mode 2 is different. It is not logical.

**Comment by FrSky-GX** [comment]
>But in Glider V-Tail the Output is different. Stick Mode 1, 3, 4 are the same. But Stick Mode 2 is different. It is not logical.

OutputMap is different based on different mode under v-tail glider? NO! they are still the same only input map is different.

**Comment by EngelMT** [comment]
Here are Screen Shots. Firmware 1.2.25L

Mode1 Input
![glider_v_mode1_input1](https://cloud.githubusercontent.com/assets/16795828/22776937/f03117ac-eeb1-11e6-9b54-77542f68d8f7.jpg)
![glider_v_mode1_input2](https://cloud.githubusercontent.com/assets/16795828/22776938/f031ee52-eeb1-11e6-886a-4bda98a149fe.jpg)

Mode1 Output
![glider_v_mode1_output1](https://cloud.githubusercontent.com/assets/16795828/22776963/064b1dd0-eeb2-11e6-922e-5b2f98cf5ec3.jpg)
![glider_v_mode1_output2](https://cloud.githubusercontent.com/assets/16795828/22776962/064675aa-eeb2-11e6-891b-d0326677031c.jpg)

Mode2 Input
![glider_v_mode2_input1](https://cloud.githubusercontent.com/assets/16795828/22776983/14f26208-eeb2-11e6-83b5-777e0381e15a.jpg)
![glider_v_mode2_input2](https://cloud.githubusercontent.com/assets/16795828/22776982/14f1a9b2-eeb2-11e6-9d0b-97bb11b77b1d.jpg)

Mode2 Output
![glider_v_mode2_output1](https://cloud.githubusercontent.com/assets/16795828/22776998/253bc870-eeb2-11e6-93a6-6a37ad81157b.jpg)
![glider_v_mode2_output2](https://cloud.githubusercontent.com/assets/16795828/22776999/253d855c-eeb2-11e6-915b-1f769b917c3e.jpg)

Mode3 Input
![glider_v_mode3_input1](https://cloud.githubusercontent.com/assets/16795828/22777025/3705b9b2-eeb2-11e6-90c6-811303437e5f.jpg)
![glider_v_mode3_input2](https://cloud.githubusercontent.com/assets/16795828/22777026/37068888-eeb2-11e6-8722-c8e70e707e18.jpg)

Mode3 Output
![glider_v_mode3_output1](https://cloud.githubusercontent.com/assets/16795828/22777040/451839a8-eeb2-11e6-809f-102c6fe3a479.jpg)
![glider_v_mode3_output2](https://cloud.githubusercontent.com/assets/16795828/22777041/451a91e4-eeb2-11e6-85b0-ac8b8078c89a.jpg)

Mode4 Input
![glider_v_mode4_input1](https://cloud.githubusercontent.com/assets/16795828/22777055/52e04954-eeb2-11e6-95d1-433f7c9911f8.jpg)
![glider_v_mode4_input2](https://cloud.githubusercontent.com/assets/16795828/22777056/52e145ca-eeb2-11e6-8ab8-6f9eab97fb94.jpg)

Mode4 Output
![glider_v_mode4_output1](https://cloud.githubusercontent.com/assets/16795828/22777072/61636326-eeb2-11e6-8a32-10c75bc725b0.jpg)
![glider_v_mode4_output2](https://cloud.githubusercontent.com/assets/16795828/22777071/615ab7b2-eeb2-11e6-86f4-62f8b98ab229.jpg)

**Comment by EngelMT** [comment]
![glider_v_tabelle](https://cloud.githubusercontent.com/assets/16795828/22777276/06fad832-eeb3-11e6-9e51-0403e945bdcf.jpg)

**Comment by Adelaxie** [comment]
Do not understand!!
Let us see CH9 of OUTPUTMAP under mode 1 2 3 4.
all the mode the output is FLP3 in your screenshot.
Why in your form, you list KLP3(assume it is FLP3) under mode 1 3 4 and QR3 under mode2  ???

**Comment by EngelMT** [comment]
I think was my mistake, sorry. Forgott all. I check it and you are right. It works.
